# This is a basic workflow to help you get started with Actions

name: Basic workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run a linter
        run: |
          echo It is a linter, world!
          
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Run a build
        run: |
          echo It is a build, world!
          exit 1
          
  build2:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Run a build2
        run: |
          echo It is a build2, world!

  deploy:
    needs: [build, build2]
    runs-on: ubuntu-latest
    steps:
      - name: Run a deploy
        run: |
          echo It is a deploy, world!

  final:
    if: always()
    needs: [lint, build, build2, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        id: workflow_status
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo It is a check status, world!
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo status=failure
            echo "status=failure" >> $GITHUB_ENV
          elif [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo status=cancelled
            echo "status=cancelled" >> $GITHUB_ENV
          else
            echo status=success
            echo "status=success" >> $GITHUB_ENV
          fi          
        # echo Lintstatus=${{ needs.lint.result }}=
        # echo Allstatus=${{ join(needs.*.result) }}=
        # echo is_failed=$is_failed=
        # echo is_canceled=$is_canceled=
        # gh api /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs | jq '.jobs[]| select (.conclusion == "failure") | .name, .head_branch, (.steps[]|select(.conclusion == "failure")|.name)'
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: 'CI Bot'
          SLACK_COLOR: ${{ steps.workflow_status.outputs.status }}
          SLACK_MESSAGE: '${{ github.workflow }} ${{ steps.workflow_status.outputs.status }}'
          SLACK_FOOTER: ''
