# This is a basic workflow to help you get started with Actions

name: Basic workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run a linter
        run: |
          echo It is a linter, world!
          
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Run a build
        run: |
          echo It is a build, world!
          sleep infinity
          exit 1
          
  build2:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Run a build2
        run: |
          echo It is a build2, world!

  deploy:
    needs: [build, build2]
    runs-on: ubuntu-latest
    steps:
      - name: Run a deploy
        run: |
          echo It is a deploy, world!

  final:
    if: always()
    needs: [lint, build, build2, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Run a deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo It is a build2, world!
          echo Lintstatus=${{ needs.lint.result }}=
          echo Allstatus=${{ join(needs.*.result) }}=
          is_failed=${{ contains(needs.*.result, 'failure') }}
          echo is_failed=$is_failed=
          is_canceled=${{ contains(needs.*.result, 'cancelled') }}
          echo is_canceled=$is_canceled=
        # gh api /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs | jq '.jobs[]| select (.conclusion == "failure") | .name, .head_branch, (.steps[]|select(.conclusion == "failure")|.name)'


      # - name: Slack Notification on failure or success
      #   uses: rtCamp/action-slack-notify@v2
      #   if: always() # Customize when this runs
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     # Optional variables for customization:
      #     SLACK_CHANNEL: '#githun_alerts'
      #     SLACK_USERNAME: 'CI Bot'
      #     SLACK_COLOR: ${{ job.status }}
      #     SLACK_MESSAGE: '${{ github.workflow }} ${{ job.status }}'
      #     SLACK_FOOTER: ''
